# Generated by Django 4.2.2 on 2023-06-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('expected_duration', models.DurationField(verbose_name='Expected Duration')),
                ('final_duration', models.DurationField(blank=True, null=True, verbose_name='Expected Duration')),
                ('coin_reward', models.PositiveIntegerField(default=0, verbose_name='Coin Reward')),
                ('fixed', models.BooleanField(default=False, verbose_name='Fixed')),
                ('finished', models.BooleanField(default=False, verbose_name='Finished')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
